import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

export const projects = pgTable('projects', {
  id: uuid('id').defaultRandom().primaryKey(), projectNumber: text('project_number').notNull(), upstreamUuid: text('upstream_uuid'), upstreamPuuid: text('upstream_puuid'),
  title: text('title'), description: text('description'), status: text('status'), municipality: text('municipality'), competentAuthority: text('competent_authority'), publicationType: text('publication_type'),
  latitude: text('latitude'), longitude: text('longitude'), publicationStartAt: timestamp('publication_start_at', { withTimezone: true }), publicationEndAt: timestamp('publication_end_at', { withTimezone: true }), appealEndAt: timestamp('appeal_end_at', { withTimezone: true }),
  isCurrentlyPublic: boolean('is_currently_public').notNull().default(true), firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
  lastCrawledAt: timestamp('last_crawled_at', { withTimezone: true }), nextCrawlAt: timestamp('next_crawl_at', { withTimezone: true }), crawlStatus: text('crawl_status').notNull().default('pending'), crawlAttempts: integer('crawl_attempts').notNull().default(0), lastCrawlError: text('last_crawl_error'), sourceMetadata: jsonb('source_metadata').notNull().default({}), ...timestamps,
}, (table) => [uniqueIndex('projects_project_number_unique').on(table.projectNumber), uniqueIndex('projects_upstream_uuid_unique').on(table.upstreamUuid), index('projects_public_idx').on(table.isCurrentlyPublic), index('projects_next_crawl_idx').on(table.nextCrawlAt)]);

export const projectPhases = pgTable('project_phases', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }), upstreamUuid: text('upstream_uuid').notNull(), phaseType: text('phase_type'), sourceMetadata: jsonb('source_metadata').notNull().default({}), firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex('project_phases_project_upstream_unique').on(table.projectId, table.upstreamUuid)]);

export const events = pgTable('events', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }), phaseId: uuid('phase_id').references(() => projectPhases.id, { onDelete: 'set null' }), upstreamUuid: text('upstream_uuid').notNull(), category: text('category'), eventCode: text('event_code'), firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(), sourceMetadata: jsonb('source_metadata').notNull().default({}) }, (table) => [uniqueIndex('events_upstream_uuid_unique').on(table.upstreamUuid), index('events_project_idx').on(table.projectId)]);

export const documents = pgTable('documents', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }), eventId: uuid('event_id').references(() => events.id, { onDelete: 'set null' }), contentId: text('content_id'), upstreamUuid: text('upstream_uuid').notNull(), sourceType: text('source_type').notNull().default('procedure_event'), category: text('category'), filename: text('filename').notNull(), description: text('description'), mimeType: text('mime_type'), sizeBytes: integer('size_bytes'), securityCategory: text('security_category'), downloadable: boolean('downloadable').notNull(), downloadStatus: text('download_status').notNull(), storageKey: text('storage_key'), sha256: text('sha256'), firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(), downloadedAt: timestamp('downloaded_at', { withTimezone: true }), attemptCount: integer('attempt_count').notNull().default(0), nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }), lastError: text('last_error'), sourceMetadata: jsonb('source_metadata').notNull().default({}), ...timestamps }, (table) => [uniqueIndex('documents_upstream_uuid_unique').on(table.upstreamUuid), index('documents_project_idx').on(table.projectId), index('documents_status_idx').on(table.downloadStatus), index('documents_next_attempt_idx').on(table.nextAttemptAt)]);

export const crawlTasks = pgTable('crawl_tasks', { id: uuid('id').defaultRandom().primaryKey(), type: text('type').notNull(), projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }), documentId: uuid('document_id').references(() => documents.id, { onDelete: 'cascade' }), payload: jsonb('payload'), status: text('status').notNull().default('pending'), priority: integer('priority').notNull().default(0), attempts: integer('attempts').notNull().default(0), maxAttempts: integer('max_attempts').notNull().default(5), nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(), lockedAt: timestamp('locked_at', { withTimezone: true }), lockedBy: text('locked_by'), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), lastError: text('last_error'), completedAt: timestamp('completed_at', { withTimezone: true }), ...timestamps }, (table) => [index('crawl_tasks_claim_idx').on(table.status, table.nextAttemptAt), index('crawl_tasks_project_idx').on(table.projectId), index('crawl_tasks_document_idx').on(table.documentId)]);

export const crawlRuns = pgTable('crawl_runs', { id: uuid('id').defaultRandom().primaryKey(), workerId: text('worker_id').notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp('finished_at', { withTimezone: true }), status: text('status').notNull().default('running'), tasksClaimed: integer('tasks_claimed').notNull().default(0), tasksCompleted: integer('tasks_completed').notNull().default(0), tasksFailed: integer('tasks_failed').notNull().default(0), projectsDiscovered: integer('projects_discovered').notNull().default(0), projectsUpdated: integer('projects_updated').notNull().default(0), documentsDiscovered: integer('documents_discovered').notNull().default(0), documentsDownloaded: integer('documents_downloaded').notNull().default(0), documentsFailed: integer('documents_failed').notNull().default(0), requestsSent: integer('requests_sent').notNull().default(0), lastError: text('last_error') });

export const crawlerState = pgTable('crawler_state', { id: integer('id').primaryKey().default(1), paused: boolean('paused').notNull().default(false), pauseReason: text('pause_reason'), lastHeartbeatAt: timestamp('last_heartbeat_at', { withTimezone: true }), lastSuccessfulUpstreamRequestAt: timestamp('last_successful_upstream_request_at', { withTimezone: true }), lastRateLimitAt: timestamp('last_rate_limit_at', { withTimezone: true }), lastDiscoveryAt: timestamp('last_discovery_at', { withTimezone: true }), currentDiscoveryCursor: jsonb('current_discovery_cursor') });

export const discoveryPartitions = pgTable('discovery_partitions', { id: uuid('id').defaultRandom().primaryKey(), strategy: text('strategy').notNull(), partitionKey: text('partition_key').notNull(), cursor: jsonb('cursor'), status: text('status').notNull().default('pending'), nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }), lastError: text('last_error'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex('discovery_partitions_unique').on(table.strategy, table.partitionKey)]);
